### ISSUE TITLE
Error while building on Ubuntu 18.10

### ISSUE THREAD

**Issue by asitemade4u** [qubus-ai/qubus#3]
- I tried building Qubus as is > error on a lot of dependencies in NPM
- then I did a `yarn` in the directory and the `node install.js` went thru with a handful of non blocking issues.
- However, the `npm run build-release` generated a lot of errors and ultimately failed.

I attach the log.
[2019-11-23T20_49_11_702Z-debug.log](https://github.com/qubus-ai/qubus/files/3882923/2019-11-23T20_49_11_702Z-debug.log)

**Comment by qubus-ai** [comment]
Thank you for reporting the issue. Could you provide more detailed information regarding " error on a lot of dependencies in NPM" ? Did you run, npm install?

The error in "npm run build-release" you reported in the attached log file was caused by utils-git script which assumes it is run in git repository. According to the log file you used cloned master branch of qubus repository, which is not git repo in fact. However, the issue was resolved, please checkout the master branch for code update.

**Comment by asitemade4u** [comment]
Thanks for the response.
However I followed the instructions to the letter:
`
git clone https://github.com/qubus-ai/qubus.git
npm install
npm run build-release
`
And I still get errors leading to not being able to install.
Please help.

**Comment by asitemade4u** [comment]
OK, found the solution.
As often with Linux, was an issue about access rights.
I just did `sudo npm install` and it worked.
Case closed.
